<a href="https://colab.research.google.com/github/ramirezcarlos292/miaad_python_programming/blob/main/practices/Pr%C3%A1ctica_17_Unidad_2_Limpieza_y_Transformaci%C3%B3n_de_Datos_Categ%C3%B3ricos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objetivo:
El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

# Instrucciones:

* Descarga el archivo CSV, nls97, proporcionado en esta tarea. También lo puedes encontrar en recursos.
* Crea un notebook en colab y guarda el archivo csv descargado en tu drive.
* Agrega secciones en el colab poniendo como título el nombre de cada ejercicio.

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [21]:
# Descargar Archivo
!wget -P /content/drive/MyDrive/ClassFiles/ https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/nls97.csv

# Leer Archivo
path_nls = r"/content/drive/MyDrive/ClassFiles/nls97.csv"

# Leer y mostrar primeros 5 renglones
df = pd.read_csv(path_nls)
df.head()

--2025-09-13 04:11:43--  https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/nls97.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7583947 (7.2M) [text/plain]
Saving to: ‘/content/drive/MyDrive/ClassFiles/nls97.csv.16’

nls97.csv.16        100%[===================>]   7.23M  46.4MB/s    in 0.2s

2025-09-13 04:11:44 (46.4 MB/s) - ‘/content/drive/MyDrive/ClassFiles/nls97.csv.16’ saved [7583947/7583947]

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
0,100061,Female,5,1980,13.0,Married,4.0,0.0,12500.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
1,100139,Male,9,1983,12.0,Married,2.0,0.0,120000.0,1 to 3 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
2,100284,Male,11,1984,7.0,Never-married,1.0,0.0,58000.0,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3,100292,Male,4,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,NaN,NaN,NaN,NaN
4,100583,Male,1,1980,13.0,Married,4.0,0.0,30000.0,Less than 1 hour a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled

# **Ejercicio 01:** Errores Tipográficos y Valores Inconsistentes: maritalstatus
* Imprime de la columna 'maritalstatus' los valores únicos.
* Imprime la frecuencia de cada valor único
* Cambia el valor 'Never-Married' a 'Single'
* Imprime la frecuencia de cada valor único.

In [23]:
print(f"Valores únicos de la columna maritalstatus")
maritalstatus = list(df.maritalstatus.unique())
for item in df.maritalstatus.unique():
  print(f"- {item}")

Valores únicos de la columna maritalstatus
- Married
- Never-married
- nan
- Divorced
- Separated
- Widowed

In [24]:
print(f"Frecuencia de cada valor único")
msdf = df.maritalstatus.value_counts().reset_index()
msdf

Imprime la frecuencia de cada valor único

   maritalstatus  count
0        Married   3066
1  Never-married   2766
2       Divorced    663
3      Separated    154
4        Widowed     23

In [25]:
null_ms = df.maritalstatus.isna().value_counts().reset_index()
null_maritalstatus = null_ms['count'].loc[null_ms['maritalstatus'] == True]
print(f"Hay {null_maritalstatus.values[0]} datos NaN in la columna 'maritalstatus'")
nan_ms = pd.DataFrame({'maritalstatus': ['Not reported'], 'count': null_maritalstatus.values[0]})

Hay 2312 datos NaN in la columna 'maritalstatus'

In [26]:
# Cambia el valor 'Never-Married' a 'Single'
df.loc[df['maritalstatus'] == 'Never-married', 'maritalstatus'] = 'Single'

In [27]:
print(f"Imprime la frecuencia de cada valor único")
msdf = df.maritalstatus.value_counts().reset_index()
msdf = pd.concat([msdf, nan_ms])
msdf.sort_values('count', ascending=False)

Imprime la frecuencia de cada valor único

  maritalstatus  count
0       Married   3066
1        Single   2766
0  Not reported   2312
2      Divorced    663
3     Separated    154
4       Widowed     23

# **Ejercicio 02:** Errores Tipográficos y Valores Inconsistentes: highestdegree.
* Imprime de la columna 'highestdegree' los valores únicos.
* Imprime la frecuencia de cada valor único
* Observa que cada valor categórico empieza con 0. Modifica las categorías para que todas estén en minúsculas y ninguna empiece con un número. Por ejemplo, si dice "2. High School", debería ser 'high school.
* Los cambios se realizarán en la misma columna 'highestdegree'.
* Imprime los nuevos valores únicos.

In [28]:
print(f"Valores únicos de la columna 'highestdegree")

for item in list(df['highestdegree'].unique()):
  print(f"- {item}")

Valores únicos de la columna 'highestdegree
- 2. High School
- 0. None
- 4. Bachelors
- 3. Associates
- 5. Masters
- 1. GED
- 7. Professional
- 6. PhD
- nan

In [29]:
print(f"Frecuencia de cada valor único")
df['highestdegree'].value_counts().reset_index()

Frecuencia de cada valor único

     highestdegree  count
0   2. High School   3667
1     4. Bachelors   1673
2           1. GED   1146
3          0. None    953
4    3. Associates    737
5       5. Masters    603
6  7. Professional    120
7           6. PhD     54

In [36]:
print(f"Frecuencia de cada valor único después de corregir columna 'highestdegree'")
df['highestdegree'] = df['highestdegree'].str.lower().str.replace(r'\d+\.' , '', regex=True)
df['highestdegree'].value_counts()

Frecuencia de cada valor único después de corregir columna 'highestdegree'

highestdegree
high school     3667
bachelors       1673
ged             1146
none             953
associates       737
masters          603
professional     120
phd               54
Name: count, dtype: int64

# **Ejercicio 03:** Alta Cardinalidad - Frecuencias Bajas
* De la columna 'maritalstatus' une las categorías Widowed y 'Single' en una categoría más general llamada 'Single/No Partner'. Crea una nueva columna, 'marital_grouped' donde aparezcan las nuevas categorías de maritalstatus.
* Imprime los valores únicos de la nueva columna 'marital_grouped'.
* Imprime la frecuencia de los valores únicos de la nueva columna 'marital_grouped'.

In [31]:
df['marital_grouped'] = df['maritalstatus'].apply(lambda x: 'Single/No Partner' if x == 'Widowed' else ('Single/No Partner' if x == 'Single' else x))

print("Nuevos valores únicos después de unir Widowed y Single")
for item in list(df['marital_grouped'].unique()):
  print(f"- {item}")

Nuevos valores únicos después de unir Widowed y Single
- Married
- Single/No Partner
- nan
- Divorced
- Separated

In [32]:
print(f"Frecuencia de los valores únicos de la nueva columna 'marital_grouped'")
df['marital_grouped'].value_counts()

Frecuencia de los valores únicos de la nueva columna 'marital_grouped'

marital_grouped
Married              3066
Single/No Partner    2789
Divorced              663
Separated             154
Name: count, dtype: int64

# **Ejercicio 04:** Tipos de Datos
* Imprime el tipo de datos de la columna gender
* Imprime la cantidad de bytes de dicha columna
* Si la columna es de tipo object, modifica a category.
* En caso de haber realizado la modificación del tipo de datos, imprime la cantidad de bytes que ocupa dicha columna con el nuevo tipo de datos.

In [33]:
print(f"Imprime el tipo de datos de la columna gender:")
df['gender'].dtype

Imprime el tipo de datos de la columna gender:

dtype('O')

In [34]:
print(f"Imprime la cantidad de bytes de dicha columna:")
print(f"Columna 'gender', usa: {df['gender'].memory_usage()/1024:.2f} Kb")

Imprime la cantidad de bytes de dicha columna:
Columna 'gender', usa: 70.32 Kb

In [35]:
df['gender'] = df['gender'].astype('category')
print(f"Imprime la cantidad de bytes de dicha columna:")
print(f"Columna 'gender', usa: {df['gender'].memory_usage()/1024:.2f} Kb")

Imprime la cantidad de bytes de dicha columna:
Columna 'gender', usa: 9.02 Kb